### ISSUE TITLE
9.2.0: `jaraco.packaging.sphinx` tries to create venv and install modules

### ISSUE THREAD

**Issue by kloczek** [jaraco/jaraco.packaging#12]
On generate `cssutils` (https://github.com/jaraco/cssutils/) documentation I found that `jaraco.packaging.sphinx` tries to create evev and install modules
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/jaraco/packaging/sphinx.py", line 52, in load_config_from_setup
    meta = _load_metadata_from_wheel() or load_metadata(root)
  File "/usr/lib/python3.8/site-packages/build/util.py", line 51, in project_wheel_metadata
    with build.env.IsolatedEnvBuilder() as env:
  File "/usr/lib/python3.8/site-packages/build/env.py", line 107, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/usr/lib/python3.8/site-packages/build/env.py", line 274, in _create_isolated_env_venv
    raise build.FailedProcessError(exc, 'Failed to create venv. Maybe try installing virtualenv.') from None
build.FailedProcessError: Failed to create venv. Maybe try installing virtualenv.
  Command '/tmp/build-env-z_inetin/bin/python3 -Im ensurepip --upgrade --default-pip' failed with return code 1
  stdout:
    Traceback (most recent call last):
      File "/usr/lib64/python3.8/runpy.py", line 185, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/lib64/python3.8/runpy.py", line 144, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/usr/lib64/python3.8/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/usr/lib64/python3.8/ensurepip/__init__.py", line 29, in <module>
        _SETUPTOOLS_VERSION = _get_most_recent_wheel_version("setuptools")
      File "/usr/lib64/python3.8/ensurepip/__init__.py", line 26, in _get_most_recent_wheel_version
        return str(max(_wheels[pkg], key=distutils.version.LooseVersion))
    ValueError: max() arg is an empty sequence


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 341, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function load_config_from_setup at 0x7f4b4813cf70> for event 'builder-inited' threw an exception (exception: Failed to create venv. Maybe try installing virtualenv.
  Command '/tmp/build-env-z_inetin/bin/python3 -Im ensurepip --upgrade --default-pip' failed with return code 1
  stdout:
    Traceback (most recent call last):
      File "/usr/lib64/python3.8/runpy.py", line 185, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/lib64/python3.8/runpy.py", line 144, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/usr/lib64/python3.8/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/usr/lib64/python3.8/ensurepip/__init__.py", line 29, in <module>
        _SETUPTOOLS_VERSION = _get_most_recent_wheel_version("setuptools")
      File "/usr/lib64/python3.8/ensurepip/__init__.py", line 26, in _get_most_recent_wheel_version
        return str(max(_wheels[pkg], key=distutils.version.LooseVersion))
    ValueError: max() arg is an empty sequence
)

Extension error (jaraco.packaging.sphinx):
Handler <function load_config_from_setup at 0x7f4b4813cf70> for event 'builder-inited' threw an exception (exception: Failed to create venv. Maybe try installing virtualenv.
  Command '/tmp/build-env-z_inetin/bin/python3 -Im ensurepip --upgrade --default-pip' failed with return code 1
  stdout:
    Traceback (most recent call last):
      File "/usr/lib64/python3.8/runpy.py", line 185, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/lib64/python3.8/runpy.py", line 144, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/usr/lib64/python3.8/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/usr/lib64/python3.8/ensurepip/__init__.py", line 29, in <module>
        _SETUPTOOLS_VERSION = _get_most_recent_wheel_version("setuptools")
      File "/usr/lib64/python3.8/ensurepip/__init__.py", line 26, in _get_most_recent_wheel_version
        return str(max(_wheels[pkg], key=distutils.version.LooseVersion))
    ValueError: max() arg is an empty sequence
)
```
Is it possible to disable that and use current env to gen documentation? 🤔 
Other question is why that modules is doing that that way?

**Comment by kloczek** [comment]
Gentle ping .. 🤔

**Comment by kloczek** [comment]
Looking on
https://github.com/jaraco/jaraco.packaging/blob/e6bec91d0741f2af191a215faeb69593860335e0/jaraco/packaging/sphinx.py#L52-L56
I think that I found flaw in code.
That part of the code is trying to use .whl archive metadata. Issue is that this routine if it is not able to find .whl tries to download it from pypi. On that path of the code issue is that what is on pypi could be in different version that what is in source tree. Second issue is that this download is done in venv.

Solution could be assumption that `jaraco.packaging.sphinx` will be called after call `build` which should store .whl in `dist/` directory.

**Comment by kloczek** [comment]
IMO the best would be try to suck necessary metadata directly from pyproject.toml file ..

**Comment by kloczek** [comment]
Looking more on the code I think that I found solution
```console
[tkloczko@pers-jacek jaraco.packaging-9.2.0]$ JARACO_PACKAGING_SPHINX_WHEEL=$(ls -1 $PWD/dist/*whl) /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [config changed ('project')] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jaraco-packaging.3 { history } done
build succeeded.

The manual pages are in build/sphinx/man.
```
Looking on generated man page I don't see anything about that possibility so as found issue is possible to mitigate using `$JARACO_PACKAGING_SPHINX_WHEEL` env variable.
Here is current content of the man page generated using above method. In that man pan page there is not to much useful details 🤔 
```man
PYTHON-JARACO-PACKAGING(3)                                                          jaraco.packaging                                                          PYTHON-JARACO-PACKAGING(3)

NAME
       python-jaraco-packaging - Python jaraco-packaging Module Documentation

HISTORY
   v9.2.0
       #7, #10, #11: Added environment variable to bypass building metadata for offline builds.

   v9.1.2
       #6: Added minimal test to sphinx.packaging.

   v9.1.1
       Change requirement to build[virtualenv] as workaround for pypa/build#266.

   v9.1.0
       Prefer build to pep517 for loading package metadata.

   v9.0.0
       Use pep517.meta to load package metadata. Adds support for packages without setup.py.

       Removed info module (and setuptools show command).

       Removed depends module. Use other packaging tools instead.

   v8.2.1
       Rely on PEP 420 for namespace package.

   v8.2.0
       Inject rst_epilog to include |project| substitution.

   v8.1.1
       Refresh package metadata.

   v8.1.0
       In sphinx when loading metadata, trap a ValueError to include the offending value.

   v8.0.0
       Require Python 3.6 or later.

   7.0
       Removed 'cheese' package as it was built for a use-case that is no longer needed, depends on deprecated functionality in setuptools, and is causing errors in tests (SSL).

   6.2
       Sphinx plugin now declares support for parallel reads (optimistically).

   6.1
       Sphinx plugin now exposes package_url in HTML templates.

   6.0
       Switch to pkgutil namespace technique for the jaraco namespace.

   5.2
       Show command now also honors direct attributes on a Distribution instance.

   5.1.1
       #2: In Sphinx module, use universal newlines to avoid broken results on Windows.

   5.1
       Added jaraco.packaging.make-tree utility for taking output from pipdeptree and making a tree of it.

   5.0
       Drop support for Python 2.6.

       Re-aligned to use pkg_resources-managed technique for the jaraco namespace, all package of which must elect one technique or another.

   4.1
       Use pkgutil for namespace package handling. Experimental process based on pypa/python-packaging-user-guide#265.

   4.0
       Remove release module.

   3.2
       Add Python 2.6 support for Sphinx extension.

   3.1
       Added Sphinx extension for loading several keys from their package metadata.

   3.0
       Removed pmxbot uploader.

   2.11
       Moved hosting to Github.

       Add support for retaining the active bookmark after updating to tagged revision for release.

   2.10
       release  script  no longer invokes register prior to the upload. Instead, the user should either set the password in .pypirc (not recommended) or use Setuptools 20.1 and keyring
       to store the password securely.

   2.9
       Add show distutils command for showing attributes of the distribution.

   2.8
       Add packaging.depends.load_dependencies.

   2.7
       Added --register option to upload-package command.

   2.4
       Added jaraco.packaging.cheese and the upload-package command from the YouGov project of the same namesake.

   2.3
       Add 'dist_commands' to config so projects released with jaraco.packaging.release can specify which dist commands are run.

   2.2
       Added depends module implementing a dependency-tree command and also a distutils Command dependency_tree.

       This module is a Sphinx plugin. Add jaraco.packaging.sphinx to conf.py, and the setup hook does the rest.

       >>> 'setup' in globals()
       True

       jaraco.packaging.sphinx.add_package_url(app, pagename, templatename, context, doctree)

       jaraco.packaging.sphinx.configure_substitutions(app)

       jaraco.packaging.sphinx.load_config_from_setup(app)
              Replace values in app.config from package metadata

       jaraco.packaging.sphinx.setup(app)

       • Index

       • Module Index

       • Search Page

AUTHOR
       Jason R. Coombs

COPYRIGHT
       Jason R. Coombs

9.2.0                                                                                 May 24, 2023                                                            PYTHON-JARACO-PACKAGING(3)
```

**Comment by jaraco** [comment]
Excellent! Glad you figured it out. Yes, that environment variable was added in the 9.2.0 release as part of #11.

**Comment by kloczek** [comment]
Tested and still it is one small warning 😋 
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [ 50%] history
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jaraco-packaging.3 { history } /home/tkloczko/rpmbuild/BUILD/jaraco.packaging-9.3.0/jaraco/packaging/sphinx.py:docstring of jaraco.packaging.sphinx.SidebarLinksDirective:1: WARNING: py:class reference target not found: sphinx.util.docutils.SphinxDirective
done
build succeeded, 1 warning.
```
